services:
  - type: web
    name: project-hive-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.projecthive.wsgi:application
    envVars:
      - key: GEMINI_API_KEY
        sync: false
    buildFilter:
      paths:
        - backend/**
    postDeployCommand: cd backend && python manage.py migrate
