services:
  - type: web
    name: project-hive-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn projecthive.wsgi:application
    envVars:
      - key: GEMINI_API_KEY
        sync: false
