# Generated by Django 5.0.6 on 2025-05-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('system_design', models.TextField()),
                ('working_principle', models.TextField()),
                ('workflow', models.TextField()),
            ],
        ),
    ]
